const mongoose=require('mongoose');
const bookingSchema=new mongoose.Schema({
  client:{type:mongoose.Schema.Types.ObjectId,
    ref:'User',
    required:true
  },
  artist:{type:mongoose.Schema.Types.ObjectId,
    ref:'Artist',
    required:true
  },
  section:{type:String,
    required:true
  },
  eventDate:{type:Date,
    required:true
  },
  eventType:{type:String,
    required:true
  },
  venue:{type:String,
    required:true
  },
  city:{type:String,
    required:true
  },
  guestCount:Number,
  budget:Number,
  phone:String,
  notes:String,
  status:{type:String,
    enum:['pending','confirmed','completed','cancelled'],
    default:'pending'
  }
},
{timestamps:true});
module.exports=mongoose.model('Booking',bookingSchema);
